version: '3'

services: 
    frontend:
        build: ./project
        environment: 
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_DATABASE: 'testdb'
        volumes: 
            - ./project:/usr/src/app
        ports:
            - 5000:5000
        command: python ./app.py

    database:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: 'testdb'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'

        volumes:
            - flask-db:/var/lib/mysql   
volumes:
    flask-db: