version: '3'

services: 
    frontend:
        build: ./project
        environment: 
            SQLALCHEMY_DATABASE_URI: '...'
        volumes: 
            - ./project:/usr/src/app
        ports:
            - 5000:5000
        command: python ./app.py

    database:
        image: mysql:8
        restart: always
        
        environment:
            MYSQL_DATABASE: 'testdb'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'

# if you need a persistent volume you can mount to to /var/lib/mysql, where by default
# MySQL writes all its data files
#
#         volumes:
#             - my-db:/var/lib/mysql   
# volumes:
#     my-db: